export default {
  common: {
    mm: "mm",
    inches: "in",
    degrees: "°",
    grams: "g",
    pounds: "lb",
    psi: "psi",
    percent: "%",
    concave: "Concave",
    convex: "Convex",
    edit: "Edit",
    add: "Add",
    update: "Update",
    cancel: "Cancel",
    name: "Name",
    actions: "Actions",
    delete: "Delete",
    export: "Export",
    import: "Import",
    language: "Language",
    hardware: "Hardware",
    zone: "Zone",
  },

  app: {
    title: "ATM Buddy",
    contributeOn: "Contribute on",
    github: "github",
    analyticsNote: "Note : I use reasonably private analytics powered by",
    analyticsExplain:
      "only to know which tools are or aren't used. If you do not want that, you can use an adblocker or",
    optOut: "click here to opt-out",
    optIn: "opt back in",
    credits: `A project by <a class="underline" href="https://lucassifoni.info">Lucas Sifoni</a>, <a class="underline" href="http://gallifrey-optics.fr">Paul Faÿs from Gallifrey Optics</a>, and <a class="underline" href="https://la3emedim.fr">Raphaël Labro from La3emedim.fr</a>`,
  },

  home: {
    subtitle:
      "Mobile-friendly collection of tools for Amateur Telescope Makers",
    aboutTitle: "About",
    aboutText:
      "This application provides specialized calculators and reference tools for Amateur Telescope Makers (ATMs). All calculations are performed client-side and work offline after initial load.",
  },

  routes: {
    home: "Home",
    spherometer: "Spherometer to ROC",
    reverseSpherometer: "ROC to Spherometer",
    sagitta: "Sagitta Calculator",
    sineTable: "Sine table",
    mpcc: "Baader MPCCIII Hyperbola",
    spraySilvering: "Spray Silvering",
    stig: "Stig Correction",
    annularRing: "Annular Ring",
    sagittaFringes: "ROC Fringes",
    pressure: "Pressure Calculator",
    comaFree: "Coma-free Radius",
    foucaultLA: "Foucault LA",
    hardware: "Hardware",
  },

  spherometer: {
    formula: "ROC = (r² + s²) / 2s ± b/2",
    rocLabel: "ROC:",
    feetRadius: "Radius of feet",
    sagitta: "Sagitta",
    ballDiameter: "Ball diameter",
    curveLabel: "Curve:",
  },

  reverseSpherometer: {
    formula: "Sagitta = ROC ± b/2 - sqrt((ROC ± b/2)² - r²)",
    sagittaLabel: "Sagitta:",
    feetRadius: "Radius of feet",
    desiredRoc: "Desired ROC",
    ballDiameter: "Ball diameter",
    curveLabel: "Curve:",
  },

  sagittaCalc: {
    formula: "Sagitta = r² / (2 × ROC)",
    sagittaLabel: "Sagitta:",
    mirrorRadius: "Mirror radius",
    rocLabel: "ROC",
  },

  sineTable: {
    formula: "Sine table: sin(x) = r / R",
    explanation:
      "Where x is the angle between the two planes.<br />r is the cup radius<br />(measure outside for a concave curve, inside for a convex curve !)",
    angleLabel: "Angle x in degrees:",
    cupRadius: "Cup radius",
    desiredRoc: "Desired ROC",
  },

  mpcc: {
    title: "Baader MPCC Conic calculator",
    explanation:
      "In waves @550nm:<br />Correction of a parabola: D (mm) / (1.1264 * (F/D)^3)<br />MPCC S.A. undercorrection: (4 / (F/D))^4 * 0.81",
    focalRatio: "Focal ratio:",
    parabolaCorrection: "Parabola correction:",
    mpccUndercorrection: "MPCC Undercorrection:",
    targetConic: "Target conic:",
    diameter: "Diameter",
    focalLength: "Focal length",
  },

  stig: {
    title: "Astigmatism correction reminder.",
    instruction:
      'Fix by following the "Polish" column with straight strokes with a full size tool.',
    axis: "Axis",
    elevation: "Elevation",
    radius: "Radius",
    fix: "Fix",
    red: "Red",
    blue: "Blue",
    high: "HIGH",
    low: "LOW",
    short: "SHORT",
    long: "LONG",
    tot: "TOT",
    mot: "MOT",
  },

  annularRing: {
    title: "Annular Ring Surface Area Calculator",
    mirrorDiameter: "Mirror diameter",
    inputMode: "Input mode:",
    normalized: "0..1",
    millimeters: "Millimeters",
    centralObstruction: "Central obstruction radius",
    zoneStart: "Zone Start radius",
    zoneEnd: "Zone End radius",
    results: "Results:",
    surfaceArea: "Surface Area:",
    ofTotalArea: "Of Total Area:",
    ofUnobstructedArea: "Of Unobstructed Area:",
    shouldFix: "Should you fix it? yes",
    visual: "Visual:",
  },

  sagittaFringes: {
    title: "ROC Fringes Calculator",
    rocLabel: "RoC of face under test:",
    invalidInput: "Invalid input values",
    lambda: "Lambda (nm):",
    contactDiameter: "Contact diameter",
    concaveRoc: "Concave caliber RoC",
    nbFringes: "Number of fringes:",
    relativeShape: "Relative shape:",
    concavity: "Concavity (+1)",
    convexity: "Convexity (-1)",
  },

  pressure: {
    formula: "M = π × r² × P - W",
    weightToAdd: "Weight to add:",
    polisherDiameter: "Polisher diameter",
    polisherWeight: "Polisher weight",
    targetPressure: "Target pressure",
    totalMass: "Total mass needed:",
    exceedsPressure: "Polisher alone exceeds target pressure",
    pressureUnit: "g/cm²",
  },

  comaFree: {
    title: "Coma-free radius calculator",
    formula: "Coma-free field diameter (mm) = 0.022 * (f/D)³",
    focalRatio: "Focal ratio:",
    fPrefix: "f/",
    comaFreeLinear: "Coma-free field (linear):",
    comaFreeApparent: "Coma-free field (apparent):",
    comaFreeEyepiece: "Coma-free in eyepiece:",
    ofAfov: "° of",
    afov: "AFOV",
    diameter: "Diameter",
    focalLength: "Focal length",
    eyepieceFl: "Eyepiece focal length",
    eyepieceAfov: "Eyepiece AFOV (°):",
  },

  foucault: {
    formulaMoving: "LA = -K × h² / 2R",
    formulaFixed: "LA = -K × h² / R",
    mirrorDiameter: "Mirror diameter",
    paraxialRoc: "Paraxial ROC (mm):",
    conicConstant: "Conic constant (K):",
    sourceConfig: "Source configuration:",
    fixedSource: "Fixed source",
    movingSource: "Moving source",
    standardZones: "Standard Zones (Tirages):",
    customZones: "Custom Zones:",
    dividingMode: "Dividing mode:",
    linear: "Linear",
    equalArea: "Equal area",
    inputMode: "Input mode:",
    normalized: "0..1",
    millimeters: "Millimeters",
    startZone: "Start zone",
    endZone: "End zone",
    numZones: "Number of zones:",
    radius: "Radius",
    la: "LA",
    relativeLa: "Relative LA",
    summary: "Summary:",
    totalLa: "Total LA (center to edge):",
    conic: "Conic:",
    movingDesc: "Moving source: source and knife edge move together",
    fixedDesc: "Fixed source: stationary light source, moving knife edge",
    sphere: "Sphere",
    parabola: "Parabola",
    oblateEllipsoid: "Oblate ellipsoid",
    prolateEllipsoid: "Prolate ellipsoid",
    hyperbola: "Hyperbola",
  },

  hardware: {
    title: "Hardware Manager",
    importExport: "Import/Export",
    exportBtn: "Export",
    importBtn: "Import",
    exportHelp:
      "Export your hardware data to backup or share with other devices. Import will merge with existing data.",
    spherometers: "Spherometers",
    feetRadius: "Feet radius",
    ballDiameter: "Ball diameter",
    feetR: "Feet R",
    ballD: "Ball D",
    noSpherometers: "No spherometers added yet.",
    opticalPieces: "Optical Pieces",
    radius: "Radius",
    roc: "ROC",
    r: "R",
    rocShort: "RoC",
    noOpticalPieces: "No optical pieces added yet.",
    polishers: "Polishers",
    diameter: "Diameter",
    weight: "Weight",
    noPolishers: "No polishers added yet.",
    confirmDeleteSpherometer:
      "Are you sure you want to delete this spherometer?",
    confirmDeleteOpticalPiece:
      "Are you sure you want to delete this optical piece?",
    confirmDeletePolisher: "Are you sure you want to delete this polisher?",
    confirmReplace: "already exists. Replace it?",
    spherometerWord: "Spherometer",
    opticalPieceWord: "Optical piece",
    polisherWord: "Polisher",
    invalidFile:
      "Invalid file format. Please select a valid ATM Buddy hardware export file.",
    importSuccess:
      "Import completed! Added {spherometers} spherometers, {opticalPieces} optical pieces, and {polishers} polishers.",
    importError: "Error reading file. Please make sure it's a valid JSON file.",
  },

  selectors: {
    loadSpherometer: "Load spherometer:",
    loadOpticalPiece: "Load optical piece:",
    loadPolisher: "Load polisher:",
    createSpherometersHint: "Create spherometers in the",
    createOpticalPiecesHint: "Create optical pieces in the",
    createPolishersHint: "Create polishers in the",
    manageSpherometersHint: "Manage spherometers in the",
    manageOpticalPiecesHint: "Manage optical pieces in the",
    managePolishersHint: "Manage polishers in the",
    tabSuffix: "tab to quickly load their dimensions here.",
    tabSuffixManage: "tab.",
  },

  spraySilvering: {
    title: "Spray silvering proportions & recipe",
    baseQuantityInfo:
      "Base quantity is 150ml distilled water + 1.6g silver nitrate.<br />Other quantities are derived from that.<br />Recipe from Gerhard S. on Cloudy Nights",
    bomTitle: "BOM for a session",
    resetBom: "Reset BOM",
    chemicalsTitle: "The chemicals",
    step0: "Step 0",
    calibrateBottles: "Calibrate bottles",
    calibrate: "Calibrate",
    bottle1: "Bottle 1",
    bottle2: "Bottle 2",
    calibrateInstruction:
      "with water, ensuring that the same quantity of water is sprayed with 100 sprays.",
    step1: "Step 1",
    prepareSolutions: "Prepare the solutions",
    baseQuantity: "Base quantity (ml):",
    solution1: "Solution 1",
    solution2: "Solution 2",
    solution3: "Solution 3",
    silverNitrate: "silver nitrate",
    distilledWater: "distilled water",
    sodiumHydroxide: "sodium hydroxide",
    glucose: "glucose",
    bottle1Info: "is the mixed solution according to below instructions.",
    bottle2Info: "contains the sugar",
    step2: "Step 2",
    mixingSilver: "Mixing of silver solution",
    becomes: "becomes",
    step2_1: "1 : Pour about",
    step2_1b: "ml of",
    step2_1c: "into a mixing bowl.",
    step2_2: "2 : Add a few drops of ammonia solution (25% dilution)",
    step2_3: "3 : Add all of",
    step2_4: "4 : Add the rest of",
    step2_4b: "(the solution will turn brown)",
    step2_5:
      "5 : Carefully add ammonia solution drop by drop while stirring until a transparent, slightly brownish solution is obtained.",
    precipitateNote:
      "Any precipitate that may still be present should be completely dissolved",
    cleaningTitle: "The cleaning and spraying",
    cleanMirror: "Clean the mirror",
    cleaningInstructions:
      "Use chalk precipitate in distilled/demin water on small cotton balls. Change often and start with thick sauce, thinning it progressively. The center will clean fast but the edge and chamfer need a LOT of time.<br /><br />Rough guideline : (diameter_in_mm/15)^1.4 = time.<br />Yes, that is an advice of 1h40 for a 400mm mirror.<br /><br />Rinse with demin water and if possible, high pressure.",
    mirrorDiameter: "Mirror diameter",
    cleaningTime: "Cleaning time :",
    sprayMirror: "Spray the mirror",
    sprayingInstructions:
      "Spray the mirror with both sprays, ensuring that they mix on the surface. You will see a faint blue film appear first.<br />Then it will turn yellowish. If you see dark brown or black streaks, this means your cleaning wasn't thorough enough.<br />A thin coating is preferable to a thick one and it should still be a tad transparent at the end.",
    dryStore: "Dry & store",
    storageInstructions:
      "Immediately dry with a hot air gun and store in an airtight box with dessicant packs, or better, silver protector felt. Silver protector felt is felt impregnated with tiny silver particles that are there to react with oxydants first and protect your coating.",
    bomGloves: "Gloves",
    bomChalk: "Chalk to wash the mirrors",
    bomMirrorStands: "Mirror stands",
    bomAntiProjection: "Anti-projection box",
    bomHairdryer: "Hairdryer",
    bomCotton: "Hydrophilic cotton",
    bomDeminWater: "Demin. water",
    bomStands: "Stands for the mirrors",
    bomSilverBox: "A box in which to silver",
    bomGlucose: "Glucose",
    bomSilverNitrate: "Silver nitrate",
    bomSodiumHydroxide: "Sodium hydroxide",
    bomAmmonia: "Ammonia",
    bomSprayers: "Two sprayers",
    bomContainers: "Containers",
    bomMasks: "FFP2 masks",
  },
};
