export default {
  common: {
    mm: "mm",
    degrees: "°",
    grams: "g",
    peRdCent: "%",
    concave: "Concave",
    convex: "Convexe",
    edit: "Modifier",
    add: "Ajouter",
    update: "Mettre à jour",
    cancel: "Annuler",
    name: "Nom",
    actions: "Actions",
    delete: "Supprimer",
    export: "Exporter",
    import: "Importer",
    language: "Langue",
    hardware: "Matériel",
    zone: "Zone",
  },

  app: {
    title: "ATM Buddy",
    contributeOn: "Contribuer sur",
    github: "github",
    analyticsNote:
      "Note : J'utilise des statistiques raisonnablement privées via",
    analyticsExplain:
      "uniquement pour savoir quels outils sont utilisés ou non. Si vous ne le souhaitez pas, vous pouvez utiliser un bloqueur de publicités ou",
    optOut: "cliquez ici pour refuser",
    optIn: "réactiver",
    credits: `Un projet par <a class="underline" href="https://lucassifoni.info">Lucas Sifoni</a>, <a class="underline" href="http://gallifrey-optics.fr">Paul Faÿs de Gallifrey Optics</a>, et <a class="underline" href="https://la3emedim.fr">Raphaël Labro de La3emedim.fr</a>`,
  },

  home: {
    subtitle:
      "Collection d'outils adaptés aux smartphones pour les opticiens amateurs",
    aboutTitle: "À propos",
    aboutText:
      "Cette application fournit des calculateurs spécialisés et des outils de référence pour les fabricants de télescopes amateurs (ATM). Tous les calculs sont effectués côté client et fonctionnent hors ligne après le premier chargement.",
  },

  routes: {
    home: "Accueil",
    spherometer: "Sphéromètre vers RdC",
    reverseSpherometer: "RdC vers Sphéromètre",
    sagitta: "Calculateur de flèche",
    sineTable: "Table sinusoïdale",
    mpcc: "Baader MPCCIII Hyperbole",
    spraySilvering: "Argenture au spray",
    stig: "Correction astigmatisme",
    annularRing: "Zones en anneaux",
    sagittaFringes: "Franges RdC",
    pressure: "Calculateur de pression",
    comaFree: "Rayon sans coma",
    foucaultLA: "Foucault LA",
    hardware: "Matériel",
  },

  spherometer: {
    formula: "RdC = (r² + s²) / 2s ± b/2",
    rocLabel: "RdC :",
    feetRadius: "Rayon des pieds (mm) :",
    sagitta: "Flèche (mm) :",
    ballDiameter: "Diamètre de la bille (mm) :",
    curveLabel: "Courbure :",
  },

  reverseSpherometer: {
    formula: "Flèche = RdC ± b/2 - sqrt((RdC ± b/2)² - r²)",
    sagittaLabel: "Flèche :",
    feetRadius: "Rayon des pieds (mm) :",
    desiredRoc: "RdC souhaité (mm) :",
    ballDiameter: "Diamètre de la bille (mm) :",
    curveLabel: "Courbure :",
  },

  sagittaCalc: {
    formula: "Flèche = r² / (2 × RdC)",
    sagittaLabel: "Flèche :",
    mirrorRadius: "Rayon du miroir (mm) :",
    rocLabel: "RdC (mm) :",
  },

  sineTable: {
    formula: "Table sinus : sin(x) = r / R",
    explanation:
      "Où x est l'angle entre les deux plans.<br />r est le rayon de la coupelle<br />(mesurez à l'extérieur pour une courbe concave, à l'intérieur pour une courbe convexe !)",
    angleLabel: "Angle x en degrés :",
    cupRadius: "Rayon de la coupelle (mm) :",
    desiredRoc: "RdC souhaité (mm) :",
  },

  mpcc: {
    title: "Calculateur conique Baader MPCC",
    explanation:
      "En ondes @550nm :<br />Correction d'une parabole : D (mm) / (1.1264 * (F/D)^3)<br />Sous-correction A.S. MPCC : (4 / (F/D))^4 * 0.81",
    focalRatio: "Rapport focal :",
    parabolaCorrection: "Correction parabole :",
    mpccUndeRdCorrection: "Sous-correction MPCC :",
    targetConic: "Conique cible :",
    diameter: "Diamètre (mm) :",
    focalLength: "Longueur focale (mm) :",
  },

  stig: {
    title: "Aide-mémoire correction d'astigmatisme.",
    instruction:
      'Corriger en suivant la colonne "Polissage" avec des courses droites avec un outil pleine taille.',
    axis: "Axe",
    elevation: "Élévation",
    radius: "Rayon",
    fix: "Correction",
    red: "Rouge",
    blue: "Bleu",
    high: "HAUT",
    low: "BAS",
    short: "COURT",
    long: "LONG",
    tot: "TOT",
    mot: "MOT",
  },

  annularRing: {
    title: "Calculateur de surface d'anneau",
    mirrorDiameter: "Diamètre du miroir (mm) :",
    inputMode: "Mode de saisie :",
    normalized: "0..1",
    millimeters: "Millimètres",
    centralObstruction: "Rayon d'obstruction centrale",
    zoneStart: "Rayon début de zone",
    zoneEnd: "Rayon fin de zone",
    results: "Résultats :",
    surfaceArea: "Surface :",
    ofTotalArea: "De la surface totale :",
    ofUnobstructedArea: "De la surface non obstruée :",
    shouldFix: "Faut-il corriger ? oui",
    visual: "Visuel :",
  },

  sagittaFringes: {
    title: "Calculateur de franges RdC",
    rocLabel: "RdC de la face testée :",
    invalidInput: "Valeurs d'entrée invalides",
    lambda: "Lambda (nm) :",
    contactDiameter: "Diamètre de contact (mm) :",
    concaveRoc: "RdC du calibre concave (mm) :",
    nbFringes: "Nombre de franges :",
    relativeShape: "Forme relative :",
    concavity: "Concavité (+1)",
    convexity: "Convexité (-1)",
  },

  pressure: {
    formula: "M = π × r² × P - W",
    weightToAdd: "Poids à ajouter :",
    polisherDiameter: "Diamètre du polissoir (mm) :",
    polisherWeight: "Poids du polissoir (g) :",
    targetPressure: "Pression cible (g/cm²) :",
    totalMass: "Masse totale nécessaire :",
    exceedsPressure: "Le polissoir seul dépasse la pression cible",
    pressureUnit: "g/cm²",
  },

  comaFree: {
    title: "Calculateur de rayon sans coma",
    formula: "Diamètre du champ sans coma (mm) = 0.022 * (f/D)³",
    focalRatio: "Rapport focal :",
    fPrefix: "f/",
    comaFreeLinear: "Champ sans coma (linéaire) :",
    comaFreeApparent: "Champ sans coma (apparent) :",
    comaFreeEyepiece: "Sans coma dans l'oculaire :",
    ofAfov: "° sur",
    afov: "AFOV",
    diameter: "Diamètre (mm) :",
    focalLength: "Longueur focale (mm) :",
    eyepieceFl: "Focale de l'oculaire (mm) :",
    eyepieceAfov: "AFOV de l'oculaire (°) :",
  },

  foucault: {
    formulaMoving: "LA = -K × h² / 2R",
    formulaFixed: "LA = -K × h² / R",
    mirrorDiameter: "Diamètre du miroir (mm) :",
    paraxialRoc: "RdC paraxial (mm) :",
    conicConstant: "Constante conique (K) :",
    sourceConfig: "Configuration de la source :",
    fixedSource: "Source fixe",
    movingSource: "Source mobile",
    standardZones: "Zones standard (Tirages) :",
    customZones: "Zones personnalisées :",
    dividingMode: "Mode de division :",
    linear: "Linéaire",
    equalArea: "Surface égale",
    inputMode: "Mode de saisie :",
    normalized: "0..1",
    millimeters: "Millimètres",
    startZone: "Zone de départ",
    endZone: "Zone de fin",
    numZones: "Nombre de zones :",
    radiusMm: "Rayon (mm)",
    laMm: "LA (mm)",
    relativeLa: "LA relatif",
    summary: "Résumé :",
    totalLa: "LA total (centre au bord) :",
    conic: "Conique :",
    movingDesc: "Source mobile : la source et le couteau se déplacent ensemble",
    fixedDesc: "Source fixe : source lumineuse stationnaire, couteau mobile",
    sphere: "Sphère",
    parabola: "Parabole",
    oblateEllipsoid: "Ellipsoïde aplati",
    prolateEllipsoid: "Ellipsoïde allongé",
    hyperbola: "Hyperbole",
  },

  hardware: {
    title: "Gestionnaire de matériel",
    importExport: "Import/Export",
    exportBtn: "Exporter",
    importBtn: "Importer",
    exportHelp:
      "Exportez vos données de matériel pour les sauvegarder ou les partager avec d'autres appareils. L'import fusionnera avec les données existantes.",
    spherometers: "Sphéromètres",
    feetRadiusMm: "Rayon des pieds (mm)",
    ballDiameterMm: "Diamètre de la bille (mm)",
    feetRMm: "R pieds (mm)",
    ballDMm: "D bille (mm)",
    noSpherometers: "Aucun sphéromètre ajouté.",
    opticalPieces: "Pièces optiques",
    radiusMm: "Rayon (mm)",
    rocMm: "RdC (mm)",
    rMm: "R (mm)",
    rocMmShort: "RdC (mm)",
    noOpticalPieces: "Aucune pièce optique ajoutée.",
    polishers: "Polissoirs",
    diameterMm: "Diamètre (mm)",
    weightG: "Poids (g)",
    noPolishers: "Aucun polissoir ajouté.",
    confirmDeleteSpherometer:
      "Êtes-vous sûr de vouloir supprimer ce sphéromètre ?",
    confirmDeleteOpticalPiece:
      "Êtes-vous sûr de vouloir supprimer cette pièce optique ?",
    confirmDeletePolisher: "Êtes-vous sûr de vouloir supprimer ce polissoir ?",
    confirmReplace: "existe déjà. Le remplacer ?",
    spherometerWord: "Le sphéromètre",
    opticalPieceWord: "La pièce optique",
    polisherWord: "Le polissoir",
    invalidFile:
      "Format de fichier invalide. Veuillez sélectionner un fichier d'export ATM Buddy valide.",
    importSuccess:
      "Import terminé ! Ajouté {spherometers} sphéromètres, {opticalPieces} pièces optiques et {polishers} polissoirs.",
    importError:
      "Erreur de lecture du fichier. Assurez-vous qu'il s'agit d'un fichier JSON valide.",
  },

  selectors: {
    loadSpherometer: "Charger un sphéromètre :",
    loadOpticalPiece: "Charger une pièce optique :",
    loadPolisher: "Charger un polissoir :",
    createSpherometersHint: "Créez des sphéromètres dans l'onglet",
    createOpticalPiecesHint: "Créez des pièces optiques dans l'onglet",
    createPolishersHint: "Créez des polissoirs dans l'onglet",
    manageSpherometersHint: "Gérez les sphéromètres dans l'onglet",
    manageOpticalPiecesHint: "Gérez les pièces optiques dans l'onglet",
    managePolishersHint: "Gérez les polissoirs dans l'onglet",
    tabSuffix: "pour charger rapidement leurs dimensions ici.",
    tabSuffixManage: ".",
  },

  spraySilvering: {
    title: "Proportions et recette d'argenture au spray",
    baseQuantityInfo:
      "La quantité de base est 150ml d'eau distillée + 1.6g de nitrate d'argent.<br />Les autres quantités en découlent.<br />Recette de Gerhard S. sur Cloudy Nights",
    bomTitle: "BOM pour une session",
    resetBom: "Réinitialiser la BOM",
    chemicalsTitle: "Les produits chimiques",
    step0: "Étape 0",
    calibrateBottles: "Calibrer les flacons",
    calibrate: "Calibrer",
    bottle1: "Flacon 1",
    bottle2: "Flacon 2",
    calibrateInstruction:
      "avec de l'eau, en s'assurant que la même quantité d'eau est pulvérisée en 100 pressions.",
    step1: "Étape 1",
    prepareSolutions: "Préparer les solutions",
    baseQuantity: "Quantité de base (ml) :",
    solution1: "Solution 1",
    solution2: "Solution 2",
    solution3: "Solution 3",
    silverNitrate: "nitrate d'argent",
    distilledWater: "eau distillée",
    sodiumHydroxide: "hydroxyde de sodium",
    glucose: "glucose",
    bottle1Info: "est la solution mélangée selon les instructions ci-dessous.",
    bottle2Info: "contient le sucre",
    step2: "Étape 2",
    mixingSilver: "Mélange de la solution d'argent",
    becomes: "devient",
    step2_1: "1 : Verser environ",
    step2_1b: "ml de",
    step2_1c: "dans un bol de mélange.",
    step2_2:
      "2 : Ajouter quelques gouttes de solution d'ammoniaque (dilution 25%)",
    step2_3: "3 : Ajouter tout",
    step2_4: "4 : Ajouter le reste de",
    step2_4b: "(la solution va brunir)",
    step2_5:
      "5 : Ajouter soigneusement la solution d'ammoniaque goutte à goutte en remuant jusqu'à obtenir une solution transparente, légèrement brunâtre.",
    precipitateNote:
      "Tout précipité encore présent doit être complètement dissous",
    cleaningTitle: "Le nettoyage et la pulvérisation",
    cleanMirror: "Nettoyer le miroir",
    cleaningInstructions:
      "Utilisez du blanc de Meudon dans de l'eau distillée/déminéralisée sur de petites boules de coton. Changez souvent et commencez avec une pâte épaisse, en la diluant progressivement. Le centre se nettoiera vite mais le bord et le chanfrein demandent BEAUCOUP de temps.<br /><br />Règle approximative : (diamètre_en_mm/15)^1.4 = temps.<br />Oui, c'est un conseil de 1h40 pour un miroir de 400mm.<br /><br />Rincer à l'eau déminéralisée et si possible, haute pression.",
    mirrorDiameter: "Diamètre du miroir en mm :",
    cleaningTime: "Temps de nettoyage :",
    sprayMirror: "Pulvériser sur le miroir",
    sprayingInstructions:
      "Pulvérisez sur le miroir avec les deux sprays, en vous assurant qu'ils se mélangent sur la surface. Vous verrez d'abord apparaître un léger film bleu.<br />Puis il deviendra jaunâtre. Si vous voyez des stries marron foncé ou noires, cela signifie que votre nettoyage n'était pas assez minutieux.<br />Un revêtement fin est préférable à un épais et il devrait encore être légèrement transparent à la fin.",
    dryStore: "Sécher et stocker",
    storageInstructions:
      "Séchez immédiatement avec un pistolet à air chaud et stockez dans une boîte hermétique avec des sachets déshydratants, ou mieux, du feutre protecteur d'argent. Le feutre protecteur d'argent est du feutre imprégné de minuscules particules d'argent qui réagissent en premier avec les oxydants pour protéger votre revêtement.",
    bomGloves: "Gants",
    bomChalk: "Blanc de Meudon pour nettoyer les miroirs",
    bomMirrorStands: "Supports de miroir",
    bomAntiProjection: "Boîte anti-projection",
    bomHairdryer: "Sèche-cheveux",
    bomCotton: "Coton hydrophile",
    bomDeminWater: "Eau démin.",
    bomStands: "Supports pour les miroirs",
    bomSilverBox: "Une boîte pour argenter",
    bomGlucose: "Glucose",
    bomSilverNitrate: "Nitrate d'argent",
    bomSodiumHydroxide: "Hydroxyde de sodium",
    bomAmmonia: "Ammoniaque",
    bomSprayers: "Deux pulvérisateurs",
    bomContainers: "Récipients",
    bomMasks: "Masques FFP2",
  },
};
